<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE phone [
	<!ELEMENT phone (handphone)+ >
	<!ELEMENT handphone (os, name, price) >
	<!ELEMENT os (#PCDATA) >
	<!ELEMENT name (#PCDATA) >
	<!ELEMENT price (#PCDATA) >
	
]>
<!-- 
	기호 : 사용횟수
	 + : 1개 이상  
	 * : 0개 이상
	 ? : 0 또는 1
	 A|B : A 또는 B 둘 중 하나만 가능
	 () : 요소를 그룹으로 선언해서 사용
	 -->
<phone>
	<handphone>
		<os>안드로이드</os>
		<name>갤럭쉬</name>
		<price>150</price>
	</handphone>
	<handphone>
		<os>ios</os>
		<name>아이폰</name>
		<price>150</price>
	</handphone>
</phone>